### ISSUE TITLE
Digital Garden link is broken

### ISSUE THREAD

**Issue by jbranchaud** [joelhooks/joelhooks-com#44]
Hey 👋 your blog is great.

I was reading [_On Writing More_](https://joelhooks.com/on-writing-more) and I tried clicking through on the _Digital Garden_ link in the first section and it is broken. The problem appears to be that it is linking to an MDX file.

https://github.com/joelhooks/joelhooks-com/blob/master/content/blog/2019-12-08--on-writing-more~~qG38AKqxq/index.mdx

**Comment by needcaffeine** [comment]
Fixed by #49.
